# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://sabid19.github.io/test1."
twitter_username: SBootstrap
github_username:  sabid19
facebook_username:  sabidbd
email_username:  sabidmail@gmail.com

# Build settings
lsi: false
safe: true
incremental: false
source: test1
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
