<<<<<<< HEAD
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
=======
# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /test1
url: "http://sabid19.github.io/test1."
twitter_username: SBootstrap
github_username:  sabid19
facebook_username:  sabidbd
email_username:  sabidmail@gmail.com

# Build settings
lsi: false
safe: true
incremental: false
source: test1
>>>>>>> origin/gh-pages
markdown: kramdown
disqus: dbyll
google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Stylish Jekyll Theme
author:
  name: dbyll
  email: dbyll@ismaildemirbilek.com
  github: dbtek
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
